title = "Hate Us Cuz They Aint Us"
baseURL = "http://HateUsCuzTheyAint.Us"
tags = ["hate", "fear", "anger"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-91420291-1"
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

publishDir = "docs"

[Params]
    tagline = "Haters Enter Here"
    author = "The Original Player Hater"
    description = "When we don't know who to hate, we hate ourselves."
    logoBig = "/images/franco.gif"
    logoSmall = "/images/franco.gif"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "TomaNistor"
    linkedin = "tomanistor"
    github = "tomanistor"
    email = ""
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "Fear"
    url  = "/#fear"
    weight = 1
[[menu.main]]
    name = "Anger"
    url  = "/#anger"
    weight = 2
[[menu.main]]
    name = "Hate"
    url  = "/#hate"
    weight = 3
[[menu.main]]
    name = "ContRact"
    url  = "/#contract"
    weight = 4
